import { spawn } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { ORPCError } from "@orpc/server";
import prisma from "@typebot.io/prisma";
import { isReadTypebotForbidden } from "@typebot.io/typebot/helpers/isReadTypebotForbidden";
import type { User } from "@typebot.io/user/schemas";
import { z } from "zod";

export const scriptFileSchema = z.object({
  id: z.string(),
  name: z.string(),
  groupName: z.string(),
  content: z.string(),
});

const getScriptsDir = (typebotId: string) =>
  path.join(os.tmpdir(), "typebot-scripts", typebotId);

// All user scripts live under src/ so the root stays clean (declarations, jsconfig)
const getSrcDir = (typebotId: string) =>
  path.join(getScriptsDir(typebotId), "src");

const MANIFEST_FILE = ".typebot-manifest.json";

// Each .js file embeds its block IDs so the user can freely move files
// without editing any manifest.
const EXTRACT_IDS_RE = /^\/\/ @typebot-id: (.+)$/gm;
// Strip legacy headers from old exports
const LEGACY_VARS_HEADER_RE = /^\/\*\*[^*]*\*\/\nconst _vars = \{\};.*\n\n/;

const extractIds = (content: string): string[] =>
  [...content.matchAll(EXTRACT_IDS_RE)].map((m) => m[1].trim());

const toVsCodeContent = (content: string, ids: string[]) => {
  const idLines = ids.map((id) => `// @typebot-id: ${id}`).join("\n");
  const body = content.replace(
    /\{\{([^}]+)\}\}/g,
    (_, varName) => `_vars["${varName}"]`,
  );
  return `${idLines}\n\n${body}`;
};

const fromVsCodeContent = (content: string) =>
  content
    .replace(/^\/\/ @typebot-id: .+\n/gm, "")
    .replace(/^\/\/ @typebot-name: .+\n/m, "") // strip legacy header
    .replace(LEGACY_VARS_HEADER_RE, "")
    .replace(/^\n+/, "")
    .replace(/_vars\["([^"]+)"\]/g, (_, varName) => `{{${varName}}}`);

const toSafeName = (name: string) =>
  (name || "untitled").replace(/[/\\:*?"<>|]/g, "-").trim() || "untitled";

const buildRelPath = (
  script: z.infer<typeof scriptFileSchema>,
  nameGroupCount: Map<string, Set<string>>,
) => {
  const safeName = toSafeName(script.name);
  const groups = nameGroupCount.get(safeName);
  // Only disambiguate with the group name when two scripts share the same name
  return groups && groups.size > 1
    ? `${safeName}-${toSafeName(script.groupName)}.js`
    : `${safeName}.js`;
};

/** Walk `dir` and return blockId → absPath for every embedded @typebot-id. */
const scanDir = (dir: string): Map<string, string> => {
  const result = new Map<string, string>();
  if (!fs.existsSync(dir)) return result;

  const walk = (current: string) => {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const abs = path.join(current, entry.name);
      if (entry.isDirectory()) {
        walk(abs);
      } else if (entry.isFile() && entry.name.endsWith(".js")) {
        for (const id of extractIds(fs.readFileSync(abs, "utf-8")))
          result.set(id, abs);
      }
    }
  };

  walk(dir);
  return result;
};

const generateDeclarations = (variables: { name: string }[]) => {
  const props = variables
    .filter((v) => v.name)
    .map((v) => `  ${JSON.stringify(v.name)}: any;`)
    .join("\n");

  return [
    "// Auto-generated by Typebot — do not edit",
    "",
    "declare const _vars: {",
    props,
    "  [key: string]: any;",
    "};",
    "",
    "declare function setVariable(name: string, value: any): void;",
    "declare function getVariable(name: string): any;",
    "",
  ].join("\n");
};

const assertAccess = async (
  typebotId: string,
  user: Pick<User, "id" | "email">,
) => {
  const typebot = await prisma.typebot.findFirst({
    where: { id: typebotId },
    include: {
      collaborators: { select: { userId: true } },
      workspace: {
        select: {
          isSuspended: true,
          isPastDue: true,
          members: { select: { userId: true } },
        },
      },
    },
  });
  if (!typebot || (await isReadTypebotForbidden(typebot, user)))
    throw new ORPCError("FORBIDDEN");
};

type Context = { user: Pick<User, "id" | "email"> };

export const handleExportScripts = async ({
  input: { typebotId, scripts, variables },
  context: { user },
}: {
  input: {
    typebotId: string;
    scripts: z.infer<typeof scriptFileSchema>[];
    variables: { name: string }[];
  };
  context: Context;
}) => {
  await assertAccess(typebotId, user);
  const dir = getScriptsDir(typebotId);
  const srcDir = getSrcDir(typebotId);
  fs.mkdirSync(srcDir, { recursive: true });

  // Find every block that already has a file somewhere in the src/ tree
  const idToAbsPath = scanDir(srcDir);
  const currentIds = new Set(scripts.map((s) => s.id));

  // Detect script names that span multiple groups — those default to shared/
  // (only applied to blocks that don't already have a file)
  const nameGroupCount = new Map<string, Set<string>>();
  for (const script of scripts) {
    if (idToAbsPath.has(script.id)) continue;
    const safeName = toSafeName(script.name);
    const groups = nameGroupCount.get(safeName) ?? new Set<string>();
    groups.add(toSafeName(script.groupName));
    nameGroupCount.set(safeName, groups);
  }

  const defaultPath = (script: z.infer<typeof scriptFileSchema>) =>
    path.join(srcDir, buildRelPath(script, nameGroupCount));

  // Group scripts by their resolved file path (handles shared files)
  const pathToScripts = new Map<string, z.infer<typeof scriptFileSchema>[]>();
  for (const script of scripts) {
    const absPath = idToAbsPath.get(script.id) ?? defaultPath(script);
    pathToScripts.set(absPath, [...(pathToScripts.get(absPath) ?? []), script]);
  }

  const manifest: Record<string, string[]> = {};

  for (const [absPath, fileScripts] of pathToScripts) {
    // Preserve IDs already embedded in the file that are still live blocks
    const existingIds = fs.existsSync(absPath)
      ? extractIds(fs.readFileSync(absPath, "utf-8")).filter((id) =>
          currentIds.has(id),
        )
      : [];
    const allIds = [
      ...new Set([...existingIds, ...fileScripts.map((s) => s.id)]),
    ];

    fs.mkdirSync(path.dirname(absPath), { recursive: true });
    fs.writeFileSync(
      absPath,
      toVsCodeContent(fileScripts[0].content, allIds),
      "utf-8",
    );

    manifest[path.relative(dir, absPath)] = allIds;
  }

  // Delete files whose linked blocks have all been removed
  for (const [blockId, absPath] of idToAbsPath) {
    if (!currentIds.has(blockId) && fs.existsSync(absPath)) {
      const remaining = extractIds(fs.readFileSync(absPath, "utf-8")).filter(
        (id) => currentIds.has(id),
      );
      if (remaining.length === 0) fs.unlinkSync(absPath);
    }
  }

  // Always regenerate the declarations file with current variables
  fs.writeFileSync(
    path.join(dir, "typebot.d.ts"),
    generateDeclarations(variables),
    "utf-8",
  );

  // Write jsconfig.json once so VS Code picks up the declarations
  const jsconfigPath = path.join(dir, "jsconfig.json");
  if (!fs.existsSync(jsconfigPath)) {
    fs.writeFileSync(
      jsconfigPath,
      JSON.stringify({ compilerOptions: { target: "ES2020" } }, null, 2),
      "utf-8",
    );
  }

  // Manifest is a human-readable reference only
  fs.writeFileSync(
    path.join(dir, MANIFEST_FILE),
    JSON.stringify(manifest, null, 2),
    "utf-8",
  );

  spawn("code", ["--new-window", dir], {
    detached: true,
    stdio: "ignore",
  }).unref();

  return { folderPath: dir };
};

export const handleImportScripts = async ({
  input: { typebotId },
  context: { user },
}: {
  input: { typebotId: string };
  context: Context;
}) => {
  await assertAccess(typebotId, user);
  const idToAbsPath = scanDir(getSrcDir(typebotId));
  if (idToAbsPath.size === 0) return [];

  return Array.from(idToAbsPath.entries()).map(([id, absPath]) => ({
    id,
    content: fromVsCodeContent(fs.readFileSync(absPath, "utf-8")),
  }));
};

/** Return relative paths (within src/) of every .js file that has no @typebot-id. */
export const handleGetUnlinkedFiles = async ({
  input: { typebotId },
  context: { user },
}: {
  input: { typebotId: string };
  context: Context;
}) => {
  await assertAccess(typebotId, user);
  const srcDir = getSrcDir(typebotId);
  if (!fs.existsSync(srcDir)) return [];

  const unlinked: { relPath: string }[] = [];

  const walk = (current: string) => {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const abs = path.join(current, entry.name);
      if (entry.isDirectory()) {
        walk(abs);
      } else if (entry.isFile() && entry.name.endsWith(".js")) {
        const content = fs.readFileSync(abs, "utf-8");
        if (extractIds(content).length === 0)
          unlinked.push({ relPath: path.relative(srcDir, abs) });
      }
    }
  };

  walk(srcDir);
  return unlinked;
};

/** Write @typebot-id: blockId into a file, removing the ID from any previous file. */
export const handleLinkFile = async ({
  input: { typebotId, relPath, blockId },
  context: { user },
}: {
  input: { typebotId: string; relPath: string; blockId: string };
  context: Context;
}) => {
  await assertAccess(typebotId, user);
  const srcDir = getSrcDir(typebotId);

  // Remove the blockId from whichever file currently claims it
  const idToAbsPath = scanDir(srcDir);
  const previousAbsPath = idToAbsPath.get(blockId);
  if (previousAbsPath && fs.existsSync(previousAbsPath)) {
    const cleaned = fs
      .readFileSync(previousAbsPath, "utf-8")
      .replace(new RegExp(`^// @typebot-id: ${blockId}\n`, "m"), "");
    fs.writeFileSync(previousAbsPath, cleaned, "utf-8");
  }

  const absPath = path.join(srcDir, relPath);
  if (!fs.existsSync(absPath)) throw new ORPCError("NOT_FOUND");

  const existing = fs.readFileSync(absPath, "utf-8");
  const updatedContent = extractIds(existing).includes(blockId)
    ? existing
    : `// @typebot-id: ${blockId}\n${existing}`;

  fs.writeFileSync(absPath, updatedContent, "utf-8");

  return { content: fromVsCodeContent(updatedContent) };
};

/** List all .js files inside src/ so the script library popover can reflect them. */
export const handleListSrcScripts = async ({
  input: { typebotId },
  context: { user },
}: {
  input: { typebotId: string };
  context: Context;
}) => {
  await assertAccess(typebotId, user);
  const srcDir = getSrcDir(typebotId);
  if (!fs.existsSync(srcDir)) return [];

  const scripts: { relPath: string; name: string }[] = [];

  const walk = (current: string) => {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const abs = path.join(current, entry.name);
      if (entry.isDirectory()) {
        walk(abs);
      } else if (entry.isFile() && entry.name.endsWith(".js")) {
        const relPath = path.relative(srcDir, abs);
        const name = path.basename(entry.name, ".js");
        scripts.push({ relPath, name });
      }
    }
  };

  walk(srcDir);
  return scripts;
};

/** Read a single file from src/ and return its Typebot-formatted content. */
export const handleGetSrcScript = async ({
  input: { typebotId, relPath },
  context: { user },
}: {
  input: { typebotId: string; relPath: string };
  context: Context;
}) => {
  await assertAccess(typebotId, user);
  const srcDir = getSrcDir(typebotId);
  const absPath = path.resolve(path.join(srcDir, relPath));
  if (!absPath.startsWith(srcDir + path.sep)) throw new ORPCError("FORBIDDEN");
  if (!fs.existsSync(absPath)) throw new ORPCError("NOT_FOUND");

  const raw = fs.readFileSync(absPath, "utf-8");
  return {
    content: fromVsCodeContent(raw),
    name: path.basename(relPath, path.extname(relPath)),
  };
};
